<?php
class testHasMethodReturnsTrueForMethodDefinedInParentInterface
    implements testHasMethodReturnsTrueForMethodDefinedInParentInterface_Interface
{

}

interface testHasMethodReturnsTrueForMethodDefinedInParentInterface_Interface
{
    function testHasMethodReturnsTrueForMethodDefinedInParentInterface();
}